### ISSUE TITLE
Not working on Windows(OS)

### ISSUE THREAD

**Issue by Zenthae** [eirslett/storybook-builder-vite#10]
the issue was mentioned on discord, but i'll rewrite it here so that other can see it, it's not working on Windows(OS), the imports path are wrong, hope it could be fixed soon ^^

```
[vite] Internal server error: Failed to resolve import "/@fsC:/Users/UserName/Desktop/projects/javascript/test-storybook/.storybook/preview.js" from "..\..\..\..\..\..\virtual:\@storybook\builder-vite\vite-app.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/vite-app.js
  8  |      import { addDecorator, addParameters, addLoader, addArgTypesEnhancer } from '@storybook/client-api';
  9  |      import { logger } from '@storybook/client-logger';
  10 |      import * as config_0 from '/@fsC:/Users/UserName/Desktop/projects/javascript/test-storybook/.storybook/preview.js'
     |                                 ^
  11 |  import * as config_1 from '/@fsC:/Users/UserName/Desktop/projects/javascript/test-storybook/node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js'
  12 |  import * as config_2 from '/@fsC:/Users/UserName/Desktop/projects/javascript/test-storybook/node_modules/@storybook/addon-docs/dist/esm/frameworks/vue3/config.js'
      at formatError (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:43549:46)
      at TransformContext.error (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:43545:19)
      at normalizeUrl (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:45157:26)
      at async TransformContext.transform (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:45285:57)
      at async Object.transform (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:43747:30)
      at async transformRequest (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:59401:29)
      at async C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:59538:32
15:18:05 [vite] Internal server error: Failed to resolve import "/@fsC:/Users/UserName/Desktop/projects/javascript/test-storybook/.storybook/preview.js" from "..\..\..\..\..\..\virtual:\@storybook\builder-vite\vite-app.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/vite-app.js
  8  |      import { addDecorator, addParameters, addLoader, addArgTypesEnhancer } from '@storybook/client-api';
  9  |      import { logger } from '@storybook/client-logger';
  10 |      import * as config_0 from '/@fsC:/Users/UserName/Desktop/projects/javascript/test-storybook/.storybook/preview.js'
     |                                 ^
  11 |  import * as config_1 from '/@fsC:/Users/UserName/Desktop/projects/javascript/test-storybook/node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js'
  12 |  import * as config_2 from '/@fsC:/Users/UserName/Desktop/projects/javascript/test-storybook/node_modules/@storybook/addon-docs/dist/esm/frameworks/vue3/config.js'
      at formatError (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:43549:46)
      at TransformContext.error (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:43545:19)
      at normalizeUrl (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:45157:26)
      at async TransformContext.transform (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:45285:57)
      at async Object.transform (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:43747:30)
      at async transformRequest (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:59401:29)
      at async C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:59538:32 (x2)
```

**Comment by Zenthae** [comment]
original, https://discord.com/channels/486522875931656193/826188253849190450/834920582411714590

a "maybe" solution

> In case it helps, there is a normalizePath exported from the vite package that should be used by plugins if there are comparisons between paths and ids. Check out [Doc](https://vitejs.dev/guide/api-plugin.html#path-normalization)
> 
> source : https://discord.com/channels/486522875931656193/826188253849190450/835028585722937373

**Comment by Zenthae** [comment]
my bad, after looking at the code in the repo, i can see that `normalizePath()` is already being used, but it's still not fixing the issue

**Comment by Zenthae** [comment]
for windows, removing the `/@fs` part was enough to fix the issue, i don't know if it has an impact on other OS though

**Comment by eirslett** [comment]
Yeah, I recently tried to fix it with normalizePath, but I don't have a Windows computer to test it on... What does the whole file URL look like in the browser when you remove `/@fs`? (If you pick one of your source files as an example)

**Comment by Zenthae** [comment]
this is one of the example files, compiled and shown in the browser under `sources/localhost:6006`

`Button.vue`

```js
import { createHotContext as __vite__createHotContext } from "/@vite/client";import.meta.hot = __vite__createHotContext("/@fs/C:/Users/UserName/Desktop/projects/javascript/test-storybook/src/stories/Button.vue");
import '/@fs/C:/Users/UserName/Desktop/projects/javascript/test-storybook/src/stories/button.css';
import { reactive, computed } from '/@fs/C:/Users/UserName/Desktop/projects/javascript/test-storybook/node_modules/storybook-builder-vite/node_modules/.vite/vue_dist_vue_esm-bundler_js.js?v=ed0c4be2';

const _sfc_main = {
  name: 'my-button',

  props: {
    label: {
      type: String,
      required: true,
    },
    primary: {
      type: Boolean,
      default: false,
    },
    size: {
      type: String,
      validator: function (value) {
        return ['small', 'medium', 'large'].indexOf(value) !== -1;
      },
    },
    backgroundColor: {
      type: String,
    },
  },

  emits: ['click'],

  setup(props, { emit }) {
    props = reactive(props);
    return {
      classes: computed(() => ({
        'storybook-button': true,
        'storybook-button--primary': props.primary,
        'storybook-button--secondary': !props.primary,
        [`storybook-button--${props.size || 'medium'}`]: true,
      })),
      style: computed(() => ({
        backgroundColor: props.backgroundColor,
      })),
      onClick() {
        emit('click');
      }
    }
  },
};

import { toDisplayString as _toDisplayString, openBlock as _openBlock, createBlock as _createBlock } from "/@fs/C:/Users/UserName/Desktop/projects/javascript/test-storybook/node_modules/storybook-builder-vite/node_modules/.vite/vue_dist_vue_esm-bundler_js.js?v=ed0c4be2"

function _sfc_render(_ctx, _cache, $props, $setup, $data, $options) {
  return (_openBlock(), _createBlock("button", {
    type: "button",
    class: $setup.classes,
    onClick: _cache[1] || (_cache[1] = (...args) => ($setup.onClick && $setup.onClick(...args))),
    style: $setup.style
  }, _toDisplayString($props.label), 7 /* TEXT, CLASS, STYLE */))
}


_sfc_main.render = _sfc_render
_sfc_main.__file = "C:/Users/UserName/Desktop/projects/javascript/test-storybook/src/stories/Button.vue"
export default _sfc_main
_sfc_main.__hmrId = "ed4d51ec"
typeof __VUE_HMR_RUNTIME__ !== 'undefined' && __VUE_HMR_RUNTIME__.createRecord(_sfc_main.__hmrId, _sfc_main)
import.meta.hot.accept(({ default: updated, _rerender_only }) => {
  if (_rerender_only) {
    __VUE_HMR_RUNTIME__.rerender(updated.__hmrId, updated.render)
  } else {
    __VUE_HMR_RUNTIME__.reload(updated.__hmrId, updated)
  }
})
```

**Comment by Zenthae** [comment]
everything seems to works fine, at least for me, the only issue i have is that i can't import `WindiCSS` but it probably has nothing to do with this 😢

**Comment by eirslett** [comment]
I'm confused now - does it work on Windows or not? Is the issue with Windows in general, or WindiCSS in specific?

**Comment by Zenthae** [comment]
To summarize,  on windows, you need to remove the `/@fs` from this line https://github.com/eirslett/storybook-builder-vite/blob/825b3b064541d89c78faf58aae08b91397ada232/packages/storybook-builder-vite/codegen-iframe-script.js#L38
for it to work, but it should be verified if removing it breaks something on other os

**Comment by eirslett** [comment]
@Zenthae Does it work if you add an extra slash? `}'/@fs/${normalizePath(el)}'` could you try that?

**Comment by Zenthae** [comment]
@eirslett it works with the extra slash.

**Comment by eirslett** [comment]
@Zenthae Try using version 0.0.6 of the plugin (I just published it now). I added the extra slash. Does it work?

**Comment by Zenthae** [comment]
it's working 👌
