### ISSUE TITLE
Version 0.1.0 maximum call size exceeded

### ISSUE THREAD

**Issue by sync** [eirslett/storybook-builder-vite#102]
Since update cannot compile anymore, worked like a charm till this update.

Failing in CI (Linux) and MacOSX

```
nfo => Loading presets
vite v2.5.10 building for production...
✓ 65 modules transformed.
[vite:react-babel] /Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/jsxDecorator.js: Maximum call stack size exceeded
file: /Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/jsxDecorator.js
ERR! RangeError: /Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/jsxDecorator.js: Maximum call stack size exceeded
ERR!     at getJSXProps (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@vitejs/plugin-react/dist/index.js:108:42)
ERR!     at getJSXNode (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@vitejs/plugin-react/dist/index.js:63:19)
ERR!     at PluginPass.CallExpression (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@vitejs/plugin-react/dist/index.js:161:22)
ERR!     at newFn (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/visitors.js:177:21)
ERR!     at NodePath._call (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/path/context.js:53:20)
ERR!     at NodePath.call (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/path/context.js:40:17)
ERR!     at NodePath.visit (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/path/context.js:90:31)
ERR!     at TraversalContext.visitQueue (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/context.js:103:16)
ERR!     at TraversalContext.visitQueue (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/context.js:109:21)
ERR!     at TraversalContext.visitQueue (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/context.js:109:21)
ERR!     at TraversalContext.visitQueue (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/context.js:109:21)
ERR!     at TraversalContext.visitQueue (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/context.js:109:21)
ERR!     at TraversalContext.visitQueue (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/context.js:109:21)
ERR!     at TraversalContext.visitQueue (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/context.js:109:21)
ERR!     at TraversalContext.visitQueue (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/context.js:109:21)
ERR!     at TraversalContext.visitQueue (/Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@babel/traverse/lib/context.js:109:21)
ERR!  RangeError: /Users/anthonymittaz/Projects/Unloan/dynamite/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/jsxDecorator.js: Maximum call stack size exceeded
```

Let me know if you want more details or any help thank you

**Comment by sync** [comment]
I am using latest published Vite version '2.5.10` and have no custom Vite config

**Comment by sync** [comment]
Could it be the babel macros plugin causing issue ? I can't run my code without it but perhaps I can try it with the sample example

**Comment by eirslett** [comment]
Could be! The Storybook sample should work!

**Comment by IanVS** [comment]
@sync Are you able to create a reproducible demo?  That would help greatly.

**Comment by sync** [comment]
Will try first thing this morning

**Comment by IanVS** [comment]
A repo that reproduces this would be very useful. Without that, it's difficult to troubleshoot.
