### ISSUE TITLE
Docs Page for Story Importing SVG Fails and Kills All Other Stories

### ISSUE THREAD

**Issue by neilchaudhuri** [eirslett/storybook-builder-vite#108]
I have many stories including one that imports an SVG file. When I view that SVG story, it looks fine. The problem is that when I go to the docs page, the docs are blank, an error appears in the console, and _all_ stories, not just the SVG one, are blank thereafter until I manually reload.

SVG loading config is this:

```
const svgPlugin = require("vite-plugin-react-svg")
...
plugins: [
				svgPlugin({
					defaultExport: "component",
					expandProps: "end",
				}),
				...config.plugins,
],
```

Error is this:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'content')
    at DocsPage.js?v=7ea512ad:45
    at handleInterpolation2 (emotion-serialize.browser.esm.js:137)
    at serializeStyles4 (emotion-serialize.browser.esm.js:251)
    at emotion-styled-base.browser.esm.js:110
    at emotion-element-a8309070.browser.esm.js:27
    at renderWithHooks (react-dom.development.js:14985)
    at updateForwardRef (react-dom.development.js:17044)
    at beginWork (react-dom.development.js:19098)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
...
react-dom.development.js:20085 The above error occurred in the <Styled(div)> component:

    at http://localhost:6006/node_modules/.vite/chunk-XILLBMUE.js?v=7ea512ad:1097:45
    at MDXProvider2 (http://localhost:6006/node_modules/.vite/chunk-WE6O4IAE.js?v=7ea512ad:119:46)
    at ThemeProvider2
    at SourceContainer (http://localhost:6006/node_modules/@storybook/addon-docs/dist/esm/blocks/SourceContainer.js:35:23)
    at DocsContainer (http://localhost:6006/node_modules/@storybook/addon-docs/dist/esm/blocks/DocsContainer.js:35:22)
```

Note FWIW I don't do anything with MDX despite the `MDXProvider2` reference in the stack trace.

**Comment by sasha-t** [comment]
@neilchaudhuri , hi!
Why are you closed this issue?

I have the same problem and I don't understand what I am doing wrong(

If you resolved this problem, can you help me?

**Comment by neilchaudhuri** [comment]
@sasha-t For me, the issue is more foundational to Storybook and its current tight coupling with Emotion 10. Their workaround, `emotionAlias: false` in main.js, only works for Webpack. So I had to revert temporarily to using Webpack rather than `storybook-builder-vite` for now

**Comment by joshwooding** [comment]
@neilchaudhuri As far as I know since `storybook-builder-vite` doesn't add a resolution alias for emotion `feature.emotionAlias` isn't needed?
