### ISSUE TITLE
Import error on vite chunk

### ISSUE THREAD

**Issue by brittneypostma** [eirslett/storybook-builder-vite#184]
[https://github.com/vitejs/vite/issues/5436](https://github.com/vitejs/vite/issues/5436) is the previous issue on Vite.js repo that seems to be a storybook-builder-vite issue.

New repo created using vite with react-ts starter. 
Setup storybook with storybook-builder-vite.
Run storybook and it opens fine, but there is an error in the console that doesn't seem to effect anything yet.

```
[vite] Internal server error: Failed to resolve import "./chunk-AB7SQRAM.js" from "node_modules/.vite/chunk-MHXLKORO.js?v=169a25a1". Does the file exist?
  Plugin: vite:import-analysis
  File: react-storybook-vite/node_modules/.vite/chunk-MHXLKORO.js?v=169a25a1
  1  |  import {
  2  |    require_react
  3  |  } from "./chunk-AB7SQRAM.js";
     |          ^
  4  |  import {
  5  |    require_object_assign
      at formatError (/Users/xbxp106/coding/react-storybook-vite/node_modules/vite/dist/node/chunks/dep-cb6d7f22.js:42629:46)
      at TransformContext.error (/Users/xbxp106/coding/react-storybook-vite/node_modules/vite/dist/node/chunks/dep-cb6d7f22.js:42625:19)
      at normalizeUrl (/Users/xbxp106/coding/react-storybook-vite/node_modules/vite/dist/node/chunks/dep-cb6d7f22.js:81360:26)
      at async TransformContext.transform (/Users/xbxp106/coding/react-storybook-vite/node_modules/vite/dist/node/chunks/dep-cb6d7f22.js:81500:57)
      at async Object.transform (/Users/xbxp106/coding/react-storybook-vite/node_modules/vite/dist/node/chunks/dep-cb6d7f22.js:42845:30)
      at async doTransform (/Users/xbxp106/coding/react-storybook-vite/node_modules/vite/dist/node/chunks/dep-cb6d7f22.js:57913:29)
```

App appears to work fine and the files seem to exist.

Problem import 
![Screen Shot 2021-12-21 at 5 48 39 PM](https://user-images.githubusercontent.com/45889730/147007558-0500f4b1-588a-4a4c-8da0-f98971e79300.png)

Problem file
![Screen Shot 2021-12-21 at 5 50 14 PM](https://user-images.githubusercontent.com/45889730/147007668-a97052d0-2bfa-4e52-8dd1-7714141ac8e6.png)

**Comment by IanVS** [comment]
@brittneypostma do you see any messages in your terminal about vite finding new dependencies and reloading?  Or any other messages in your terminal?

**Comment by brittneypostma** [comment]
@IanVS this is what I see right before the error 
![image](https://user-images.githubusercontent.com/45889730/147124445-f8bdde2d-c27d-4d71-bfe9-24a0e59ac1cb.png)

**Comment by IanVS** [comment]
Ah hah, yeah it's important for vite to find and pre-bundle all the dependencies at once.  We get a lot of issues related to this, we might need to find some way to have a better error message.

You'll want to add `classnames/bind` to your list of `optimizeDeps.include` in `viteFinal`.

**Comment by brittneypostma** [comment]
Thank you! I'll try this.

**Comment by brittneypostma** [comment]
That did it, it took me awhile to figure out where the `viteFinal` was supposed to go. Just beginning to work with storybook and vite. Thanks for the help.

**Comment by IanVS** [comment]
Glad it's working, thanks for letting us know.
