### ISSUE TITLE
Can't run Storybook with CSF 3.0

### ISSUE THREAD

**Issue by sakito21** [eirslett/storybook-builder-vite#203]
I get an error when using the automatic title generation feature in storybook-builder-vite and CSF3.

```js
// main.js

module.exports = {
  stories: [
    { directory: '../stories', files: '*.story.jsx', titlePrefix: 'foo' }
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  "framework": "@storybook/react",
  core: {
    builder: 'storybook-builder-vite',
  },
  features: {
    storyStoreV7: true,
  },
  async viteFinal(config, { configType }) {
    return config;
  },
}
```

Error log
```
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at validateString (node:internal/validators:119:11)
ERR!     at Object.isAbsolute (node:path:1157:5)
ERR!     at /Users/sakito/Project/storybook-vite/node_modules/storybook-builder-vite/optimizeDeps.js:8:42
ERR!     at Array.map (<anonymous>)
ERR!     at module.exports.getOptimizeDeps (/Users/sakito/Project/storybook-vite/node_modules/storybook-builder-vite/optimizeDeps.js:7:15)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async createViteServer (/Users/sakito/Project/storybook-vite/node_modules/storybook-builder-vite/vite-server.js:35:23)
ERR!     at async Object.start (/Users/sakito/Project/storybook-vite/node_modules/storybook-builder-vite/index.js:33:20)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/sakito/Project/storybook-vite/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/Users/sakito/Project/storybook-vite/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/sakito/Project/storybook-vite/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at validateString (node:internal/validators:119:11)
ERR!     at Object.isAbsolute (node:path:1157:5)
ERR!     at /Users/sakito/Project/storybook-vite/node_modules/storybook-builder-vite/optimizeDeps.js:8:42
ERR!     at Array.map (<anonymous>)
ERR!     at module.exports.getOptimizeDeps (/Users/sakito/Project/storybook-vite/node_modules/storybook-builder-vite/optimizeDeps.js:7:15)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async createViteServer (/Users/sakito/Project/storybook-vite/node_modules/storybook-builder-vite/vite-server.js:35:23)
ERR!     at async Object.start (/Users/sakito/Project/storybook-vite/node_modules/storybook-builder-vite/index.js:33:20)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/sakito/Project/storybook-vite/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/Users/sakito/Project/storybook-vite/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/sakito/Project/storybook-vite/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5) {
ERR!   code: 'ERR_INVALID_ARG_TYPE'
ERR! }
```

This is a sample repository.
https://github.com/sakito21/storybook-vite

I think it is similar to this issue.
https://github.com/storybookjs/storybook/issues/15972

**Comment by IanVS** [comment]
This should be fixed by https://github.com/eirslett/storybook-builder-vite/pull/182.
