### ISSUE TITLE
Can't build the example with React

### ISSUE THREAD

**Issue by rqbazan** [eirslett/storybook-builder-vite#31]
### Reproduction: 

1. Clone this repo: `git clone https://github.com/eirslett/storybook-builder-vite.git`
2. Go to the React example folder: `cd storybook-builder-vite/packages/example-react`
3. Install packages: `npm i` 
4. Try to build the storybook app: `npm run build-storybook` 💥🐛

### Logs: 
```node
🚀 npm run build-storybook

> example-react@0.0.7 build-storybook D:\Software\Github\storybook-builder-vite\packages\example-react
> build-storybook

info @storybook/react v6.3.0-rc.10
info
info => Cleaning outputDir: D:\Software\Github\storybook-builder-vite\packages\example-react\storybook-static
info => Loading presets
ERR! Addon value should end in /register OR it should be a valid preset https://storybook.js.org/docs/react/addons/writing-presets/
ERR! @storybook/addon-links
vite v2.3.7 building for production...
transforming (1154) node_modules\@popperjs\core\lib\dom-utils\isTableElement.jsConflicting namespaces: "node_modules\@storybook\client-api\dist\esm\index.js" re-exports "combineParameters" from both "node_modules\@storybook\client-api\dist\esm\index.js" and "node_modules\@storybook\client-api\dist\esm\parameters.js" (will be ignored)
Conflicting namespaces: "node_modules\@storybook\components\dist\esm\index.js" re-exports "components" from both "node_modules\@storybook\components\dist\esm\index.js" and "node_modules\@storybook\components\dist\esm\typography\DocumentFormatting.js" (will be ignored)
Conflicting namespaces: "node_modules\@storybook\addon-docs\dist\esm\blocks\index.js" re-exports "SourceState" from both "node_modules\@storybook\addon-docs\dist\esm\blocks\Canvas.js" and "node_modules\@storybook\addon-docs\dist\esm\blocks\Source.js" (will be ignored)
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
✓ 1180 modules transformed.
rendering chunks (7)...[vite:build-html] The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../iframe.html".
ERR! Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../iframe.html".
ERR!     at error (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\rollup\dist\shared\rollup.js:164:30)
ERR!     at FileEmitter.emitFile (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\rollup\dist\shared\rollup.js:12942:24)
ERR!     at Object.generateBundle (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:24622:22)
ERR!     at async Bundle.generate (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\rollup\dist\shared\rollup.js:13388:9)
ERR!     at async handleGenerateWrite (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\rollup\dist\shared\rollup.js:20791:23)
ERR!     at async doBuild (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:45406:20)
ERR!     at async build (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:45230:16)
ERR!     at async build (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\storybook-builder-vite\build.js:27:5)
ERR!     at async Promise.all (index 1)
ERR!     at async buildStaticStandalone (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\@storybook\core-server\dist\cjs\build-static.js:141:28)
ERR!     at async buildStatic (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\@storybook\core-server\dist\cjs\build-static.js:161:5)
ERR!  Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../iframe.html".
ERR!     at error (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\rollup\dist\shared\rollup.js:164:30)
ERR!     at FileEmitter.emitFile (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\rollup\dist\shared\rollup.js:12942:24)
ERR!     at Object.generateBundle (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:24622:22)
ERR!     at async Bundle.generate (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\rollup\dist\shared\rollup.js:13388:9)
ERR!     at async handleGenerateWrite (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\rollup\dist\shared\rollup.js:20791:23)
ERR!     at async doBuild (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:45406:20)
ERR!     at async build (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:45230:16)
ERR!     at async build (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\storybook-builder-vite\build.js:27:5)
ERR!     at async Promise.all (index 1)
ERR!     at async buildStaticStandalone (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\@storybook\core-server\dist\cjs\build-static.js:141:28)
ERR!     at async buildStatic (D:\Software\Github\storybook-builder-vite\packages\example-react\node_modules\@storybook\core-server\dist\cjs\build-static.js:161:5) {
ERR!   code: 'PLUGIN_ERROR',
ERR!   pluginCode: 'VALIDATION_ERROR',
ERR!   plugin: 'vite:build-html',
ERR!   hook: 'generateBundle'
ERR! }
```

### System Info:

```node
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 4.82 GB / 15.87 GB
  Binaries:
    Node: 12.22.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.41)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    vite: ^2.3.7 => 2.3.7
```

**Comment by IanVS** [comment]
We are using yarn workspaces, could you try using yarn to do the installation?  `rm -rf **/node_modules` and then `yarn install`

**Comment by rqbazan** [comment]
Hey @IanVS 👋, I've re-cloned the project to has a fresh start, and seems that using npm isn't the problem 😕 because the same output appears after installing all the dependencies with Yarn.

<details>
 <summary>Click to see the output after using Yarn</summary>

```node
🚀 yarn build-storybook
info @storybook/react v6.3.0-rc.4
info
info => Cleaning outputDir: D:\Software\Github\storybook-builder-vite\packages\example-react\storybook-static
info => Loading presets
vite v2.3.7 building for production...
transforming (1170) ..\..\node_modules\lodash\noop.jsConflicting namespaces: "..\..\node_modules\@storybook\client-api\dist\esm\index.js" re-exports "combineParameters" from both "..\..\node_modules\@storybook\client-api\dist\esm\index.js" and "..\..\node_modules\@storybook\client-api\dist\esm\parameters.js" (will be ignored)
Conflicting namespaces: "..\..\node_modules\@storybook\components\dist\esm\index.js" re-exports "components" from both "..\..\node_modules\@storybook\components\dist\esm\index.js" and "..\..\node_modules\@storybook\components\dist\esm\typography\DocumentFormatting.js" (will be ignored)
Conflicting namespaces: "..\..\node_modules\@storybook\addon-docs\dist\esm\blocks\index.js" re-exports "SourceState" from both "..\..\node_modules\@storybook\addon-docs\dist\esm\blocks\Canvas.js" and "..\..\node_modules\@storybook\addon-docs\dist\esm\blocks\Source.js" (will be ignored)
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
✓ 1190 modules transformed.
rendering chunks (7)...[vite:build-html] The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../iframe.html".
ERR! Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../iframe.html".
ERR!     at error (D:\Software\Github\storybook-builder-vite\node_modules\rollup\dist\shared\rollup.js:7917:30)
ERR!     at FileEmitter.emitFile (D:\Software\Github\storybook-builder-vite\node_modules\rollup\dist\shared\rollup.js:12919:24)
ERR!     at Object.generateBundle (D:\Software\Github\storybook-builder-vite\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:24622:22)
ERR!     at async Bundle.generate (D:\Software\Github\storybook-builder-vite\node_modules\rollup\dist\shared\rollup.js:13365:9)
ERR!     at async handleGenerateWrite (D:\Software\Github\storybook-builder-vite\node_modules\rollup\dist\shared\rollup.js:20751:23)
ERR!     at async doBuild (D:\Software\Github\storybook-builder-vite\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:45406:20)
ERR!     at async build (D:\Software\Github\storybook-builder-vite\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:45230:16)
ERR!     at async build (D:\Software\Github\storybook-builder-vite\packages\storybook-builder-vite\build.js:27:5)
ERR!     at async Promise.all (index 1)
ERR!     at async buildStaticStandalone (D:\Software\Github\storybook-builder-vite\node_modules\@storybook\core-server\dist\cjs\build-static.js:141:28)
ERR!     at async buildStatic (D:\Software\Github\storybook-builder-vite\node_modules\@storybook\core-server\dist\cjs\build-static.js:161:5)
ERR!  Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../iframe.html".
ERR!     at error (D:\Software\Github\storybook-builder-vite\node_modules\rollup\dist\shared\rollup.js:7917:30)
ERR!     at FileEmitter.emitFile (D:\Software\Github\storybook-builder-vite\node_modules\rollup\dist\shared\rollup.js:12919:24)
ERR!     at Object.generateBundle (D:\Software\Github\storybook-builder-vite\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:24622:22)
ERR!     at async Bundle.generate (D:\Software\Github\storybook-builder-vite\node_modules\rollup\dist\shared\rollup.js:13365:9)
ERR!     at async handleGenerateWrite (D:\Software\Github\storybook-builder-vite\node_modules\rollup\dist\shared\rollup.js:20751:23)
ERR!     at async doBuild (D:\Software\Github\storybook-builder-vite\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:45406:20)
ERR!     at async build (D:\Software\Github\storybook-builder-vite\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:45230:16)
ERR!     at async build (D:\Software\Github\storybook-builder-vite\packages\storybook-builder-vite\build.js:27:5)
ERR!     at async Promise.all (index 1)
ERR!     at async buildStaticStandalone (D:\Software\Github\storybook-builder-vite\node_modules\@storybook\core-server\dist\cjs\build-static.js:141:28)
ERR!     at async buildStatic (D:\Software\Github\storybook-builder-vite\node_modules\@storybook\core-server\dist\cjs\build-static.js:161:5) {
ERR!   code: 'PLUGIN_ERROR',
ERR!   pluginCode: 'VALIDATION_ERROR',
ERR!   plugin: 'vite:build-html',
ERR!   hook: 'generateBundle'
ERR! }
```
</details>

**Comment by IanVS** [comment]
I just built successfully on mac after pulling main cleaning node_modules, and reinstalling.  I wonder if this is a windows/mac difference somehow...

**Comment by rqbazan** [comment]
Maybe, could I suggest adding a step in the workflow to test the build process of the examples? Also, we can add a matrix to test against mac, windows, and linux, [something like this](https://github.com/formium/tsdx/blob/462af2d002987f985695b98400e0344b8f2754b7/templates/basic/.github/workflows/main.yml)

**Comment by IanVS** [comment]
Yes I think that would be a great idea.  Are you willing to submit a PR for it?

**Comment by rqbazan** [comment]
>Are you willing to submit a PR for it?

Sure, I'll do it today or tomorrow at the latest

**Comment by schalk-b** [comment]
I tracked the issue down to https://github.com/vitejs/vite/blob/4112c5d103673b83c50d446096086617dfaac5a3/packages/vite/src/node/plugins/html.ts#L385

`const shortEmitName = path.posix.relative(config.root, id)`
id: `iframe.html`
windows: `shortEmitName = '../../iframe.html'`
mac: `shortEmitName = 'iframe.html'`

I believe vite  expects the `config.build.rollupOptions` to be an absolute path. Instead of using a _virtual_ input of iframe.html - I think it's better to provide the absolute path and then add a rollup plugin to set the output as `iframe.html`

**Comment by eirslett** [comment]
Is there a way to solve this problem and still use a "virtual input"? The thing with virtual input was done to prevent potential collisions, if a user for some reason has an _actual_, unrelated file called `iframe.html` in their repository... (I know it's somewhat of an edge case)

**Comment by husayt** [comment]
I have exactly the same poblem with vue project on windows and pnpm.

> [vite:build-html] The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../iframe.html".
> ERR! Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../iframe.html".

Hope this will fix it.

**Comment by mitow7821** [comment]
Error is gone, storybook is building, but after deploy i am getting 404 

![image](https://user-images.githubusercontent.com/34492112/123802774-effa3b00-d8eb-11eb-806f-79bc374aedfd.png)

Second problem is that while im trying to deploy stories with chromatic, its doesnt build giving no errors.

**Comment by IanVS** [comment]
@mitow7821 would you mind opening a new issue for this one so it doesn't get lost in the shuffle?  Thanks!
