### ISSUE TITLE
Support with Ember

### ISSUE THREAD

**Issue by gossi** [eirslett/storybook-builder-vite#49]
Hey there,

thanks a lot for getting startet with vite and storybook. I was eager to try it out with ember today.

Some facts about my storybook setup:

- I do not use mdx (not suitable for me/ember)
- I do not use `@storybook/addon-docs` addon (for mostly the same reason)

Things I _had_ to do when installing:

- Manually add `@mdx-js/react` dependency to my package
- Manually add `@storybook/addon-docs` dependency to my package

Seems like, this package relies on them, without making them a dependency.

After adding them, I at least could start storybook. I have a markdown -> story transformation, so I can write docs in markdown only. This seems like to be a problem for vite (?) to pick it up? At least, this is where I'm seeing errors:

```bash
13:09:10 [vite] new dependencies found: @storybook/ember, updating...
13:09:12 [vite] ✨ dependencies updated, reloading page...
13:09:13 [vite] Internal server error: unknown: Expected corresponding JSX closing tag for <br>. (23:62)

  21 | <p parentName="li"><a parentName="p" {...{"href":"https://gos.si/blog/full-featured-themes-in-figma/"}}>{`Full Featured Themes in Figma`}</a><br>{`
  22 | This article will talk about design tokens, references of such and different
> 23 | contexts within one theme and how to organize them in Figma.`}</p>
     |                                                               ^
  24 | </li>
  25 | <li parentName="ul">
  26 | <p parentName="li"><a parentName="p" {...{"href":"https://gos.si/blog/say-hello-to-theemo-the-yordle-powered-theme-automator/"}}>{`Say Hello to Theemo – the Yordle Powered Theme
  Plugin: vite-plugin-mdx
  File: /Users/thomas/code/hokulea/hokulea/documentation/backstage/making-of.md
  27 |
  28 |  - [Integrate Ember with the JS Ecosystem at the Example of
  29 |    Theemo](https://gos.si/blog/integrate-ember-with-the-js-ecosystem-at-the-example-of-theemo/)<br>
     |                                                     ^
  30 |    Explains how to bring design tokens from Figma to Ember and develop libraries
  31 |    for the greater npm system rather for ember only.
      at Object._raise (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:816:17)
      at Object.raiseWithData (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:809:17)
      at Object.raise (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:770:17)
      at Object.jsxParseElementAt (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5207:16)
      at Object.jsxParseElementAt (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5175:32)
      at Object.jsxParseElementAt (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5175:32)
      at Object.jsxParseElementAt (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5175:32)
      at Object.jsxParseElementAt (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5175:32)
      at Object.jsxParseElement (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5233:17)
      at Object.parseExprAtom (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5240:19)
      at Object.parseExprSubscripts (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:10878:23)
      at Object.parseUpdate (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:10858:21)
      at Object.parseMaybeUnary (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:10836:23)
      at Object.parseExprOps (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:10693:23)
      at Object.parseMaybeConditional (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:10667:23)
      at Object.parseMaybeAssign (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:10630:21)
```

And this one:

```bash
13:09:13 [vite] Internal server error: unknown: Unexpected token (14:72)

  12 | <pre><code parentName="pre" {...{"className":"language-typescript"}}>{`export default class CheckboxComponent extends Component<CheckboxArgs>
  13 | `}</code></pre>
> 14 | <b>Extends:</b> Component&lt;[CheckboxArgs](./controls.checkboxargs.md)<!-- -->&gt;
     |                                                                         ^
  15 | <h2>{`Remarks`}</h2>
  16 | <p><a parentName="p" {...{"href":"https://www.figma.com/file/Fq29S0hD3i38bAjYz3wWwy/Components?node-id=404%3A411"}}>{`Design in Figma`}</a></p>
  17 | <h2>{`Example 1`}</h2>
  Plugin: vite-plugin-mdx
  File: /Users/thomas/code/hokulea/hokulea/api/controls.checkboxcomponent.md
  35 |  ## Example 2
  36 |
  37 |  Sizing - Use `font-size` for sizing. Using the [style modifier](https://github.com/jelhan/ember-style-modifier) in this example:
     |        ^
  38 |
  39 |  ```hbs
      at Object._raise (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:816:17)
      at Object.raiseWithData (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:809:17)
      at Object.raise (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:770:17)
      at Object.unexpected (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:9905:16)
      at Object.jsxParseIdentifier (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5018:12)
      at Object.jsxParseNamespacedName (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5028:23)
      at Object.jsxParseElementName (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5039:21)
      at Object.jsxParseOpeningElementAt (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5126:22)
      at Object.jsxParseElementAt (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5159:33)
      at Object.jsxParseElementAt (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5175:32)
      at Object.jsxParseElement (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5233:17)
      at Object.parseExprAtom (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:5240:19)
      at Object.parseExprSubscripts (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:10878:23)
      at Object.parseUpdate (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:10858:21)
      at Object.parseMaybeUnary (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:10836:23)
      at Object.parseExprOps (/Users/thomas/code/hokulea/hokulea/node_modules/@babel/parser/lib/index.js:10693:23)
```

References to my storybook (which is OSS)

- https://github.com/hokulea/hokulea/tree/main/explorer/.storybook

this is showing storybook 6.1, I tried locally with 6.3 and the loaders listed above haven't changed since then.

**Comment by eirslett** [comment]
I suspect that this will be fixed by https://github.com/eirslett/storybook-builder-vite/pull/42 but I'm not 100 % sure.

**Comment by eirslett** [comment]
@gossi can you please test once more, with the newest version of the plugin, Vite and Storybook?

**Comment by SnosMe** [comment]
Using it in **Vue** project. Still requires me to install `@mdx-js/react` 
```
Error: [vite-plugin-mdx] "@mdx-js/react" must be installed)
```

**Comment by gossi** [comment]
@eirslett Thanks for working on that. Will be off on vacation soon. So earliest will get back to it mid/end august. I'm super keen to get this running, so defo will continue on this. Ideally, when the branch I tried this on is merged, I can create a repro from that 👍
