### ISSUE TITLE
If import module in stories with custom resolve alias its throw an error

### ISSUE THREAD

**Issue by Asim-Tahir** [eirslett/storybook-builder-vite#8]
**Describe the bug**
Vite builder doesn't read `vite.config.ts`. Custom resolve alias defined in `vite.config.ts`.
If import module in stories with custom resolve alias its throw an error. 
E.g. : `import HelloWorld from "@/components/HelloWorld.vue"`
```log
12:23:48 AM [vite] Internal server error: Failed to resolve import "@/components/HelloWorld.vue" from "src/stories/HelloWorld.stories.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /mnt/d/Programming/NodeJS/repro/storybook-vite-builder-custom-resolver-alias/src/stories/HelloWorld.stories.js
  1  |  import HelloWorld from "@/components/HelloWorld.vue";
     |                          ^
  2  |  
  3  |  export default {
      at formatError (/mnt/d/Programming/NodeJS/repro/storybook-vite-builder-custom-resolver-alias/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:43549:46)
      at TransformContext.error (/mnt/d/Programming/NodeJS/repro/storybook-vite-builder-custom-resolver-alias/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:43545:19)
      at normalizeUrl (/mnt/d/Programming/NodeJS/repro/storybook-vite-builder-custom-resolver-alias/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:45157:26)
      at async TransformContext.transform (/mnt/d/Programming/NodeJS/repro/storybook-vite-builder-custom-resolver-alias/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:45285:57)
      at async Object.transform (/mnt/d/Programming/NodeJS/repro/storybook-vite-builder-custom-resolver-alias/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:43747:30)
      at async transformRequest (/mnt/d/Programming/NodeJS/repro/storybook-vite-builder-custom-resolver-alias/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:59401:29)
      at async /mnt/d/Programming/NodeJS/repro/storybook-vite-builder-custom-resolver-alias/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:59538:32
```

**Repro Repo**
[Github Repo](https://github.com/Asim-Tahir/storybook-vite-builder-custom-resolver-alias)

**Expected behavior**
Vite builder should be resolve custom alias without error.

**Comment by eirslett** [comment]
@Asim-Tahir Can you see if version 0.0.5 of the builder works for you? I added a config option to tweak the Vite config:

https://github.com/eirslett/storybook-builder-vite#customize-vite-config

**Comment by eirslett** [comment]
Closing this - feel free to reopen if it's still an issue.
